# Makefile for String Library Test Suite
# Exercises all functions in string.c, ctype.c, and stdlib.c
SRC_C   := ../../lib/src/uart.c ../../lib/src/string.c ../../lib/src/ctype.c ../../lib/src/stdlib.c strings_test.c
include ../../common/common.mk
