# Makefile for Memory Test application
# Tests arena allocator and malloc/free implementations
SRC_C   := ../../lib/src/uart.c ../../lib/src/string.c ../../lib/src/memory.c memory_test.c
include ../../common/common.mk
