# Makefile for packet parser application
# Compiles packet parsing demo that processes FIX protocol messages
SRC_C := ../../lib/src/uart.c ../../lib/src/string.c ../../lib/src/ctype.c ../../lib/src/stdlib.c ../../lib/src/fix.c packet_parser_simple.c
include ../../common/common.mk
